version: '3.8'

services:
  # Serviço do Backend
  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: npm run dev

  # Serviço do Frontend
  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "8080:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev
    depends_on:
      - backend

volumes:
  db_data: # Este volume era para o DB do backend, pode ser removido se não for usado