version: '3.8'

services:
  # Serviço do Backend
  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app 
      - backend_node_modules:/app/node_modules

  # Serviço do Frontend
  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "8080:80" 
    depends_on:
      - backend

# Define o volume nomeado que usamos acima
volumes:
  backend_node_modules: